version: 2.1
orbs:
  lucos: lucos/deploy@0
workflows:
  version: 2
  build-deploy:
    jobs:
      - lucos/build-arm
      - lucos/deploy-xwing:
          requires:
            - lucos/build-arm
          filters:
            branches:
              only:
                - main